services:
  postgres:
    container_name: postgres_container
    image: postgres:12.20-alpine3.20
    hostname: localhost
    environment:
      POSTGRES_USER: mintesnot
      POSTGRES_PASSWORD: mintesnot
      POSTGRES_DB: note
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  go:
    container_name: go_container
    build: 
      context: ./go-application
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
